### ISSUE TITLE
*-0.6 version leaks source maps into production.

### ISSUE THREAD

**Issue by strelec** [vmunier/akka-http-scalajs.g8#7]
Steps to reproduce:
1. Uncomment stuff in plugins.sbt.
2. Uncompress web-assets jar.
3. See *.map file there.

Even adding this does not help:```
	emitSourceMaps in Compile := false,
	scalaJSLinkerConfig in Compile ~= { _.withSourceMap(false) }
```

**Comment by vmunier** [comment]
Hi @strelec,
Apologies for responding more than one year later. This should be fixed when using sbt-web-scalajs `v1.0.11` (relevant commit https://github.com/vmunier/sbt-web-scalajs/commit/b24b8d79aa82f6bdb89046cc8595ebf8fd340f8a).
akka-http-scalajs.g8 has also been updated to use sbt-web-scalajs `v1.0.11`.
